import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { assessTaskRisk, enforceApprovalGate, parseApprovalResponse, type ApprovalGateTask } from "./approval-gate";
import { parseEngineerReport } from "./orchestrator";

const ENGINEER_REPORT_PATH = "logs/engineer-report-latest.md";
const HUMAN_CONFIRMATION_REQUIRED_PATH = "agent-memory/human-confirmation-required.md";
const HUMAN_CONFIRMATION_LOG_PATH = "logs/human-confirmation.md";
const APPROVAL_RESPONSE_PATH = "agent-memory/approval-response.md";

export interface HumanConfirmationResult {
  task: ApprovalGateTask;
  required: boolean;
  approved: boolean;
  reason: string;
}

export function runHumanConfirmationFlow(projectRoot: string): HumanConfirmationResult {
  ensureDirs(projectRoot);
  const generatedAt = new Date().toISOString();
  const engineerReport = readOptional(projectRoot, ENGINEER_REPORT_PATH);
  const report = parseEngineerReport(engineerReport);
  const task = taskFromReport(report, generatedAt);
  const gate = enforceApprovalGate(projectRoot, task, generatedAt);
  const approvals = parseApprovalResponse(readOptional(projectRoot, APPROVAL_RESPONSE_PATH));
  const token = approvals.find((approval) => approval.taskId === task.id && approval.status === "approved");
  const required = gate.action !== "allow";
  const result: HumanConfirmationResult = {
    task: gate.task,
    required,
    approved: Boolean(token),
    reason: token ? token.approvalReason : gate.task.blockedReason ?? gate.message,
  };

  writeFileSync(join(projectRoot, HUMAN_CONFIRMATION_REQUIRED_PATH), renderConfirmationRequired(result, generatedAt), "utf8");
  writeFileSync(join(projectRoot, HUMAN_CONFIRMATION_LOG_PATH), renderConfirmationLog(result, generatedAt), "utf8");
  return result;
}

function taskFromReport(report: ReturnType<typeof parseEngineerReport>, generatedAt: string): ApprovalGateTask {
  const summary = report.taskSummary.replace(/\n/g, " ").slice(0, 120);
  const riskText = [...report.risks, ...report.humanApprovalNeeded, ...report.filesChanged].join(" ");
  return {
    id: "human-confirmation-from-engineer-report",
    title: summary || "Review latest Codex Engineer report",
    goal: `GPT PM should review Codex output and ask Human Vision Owner if needed. ${riskText}`,
    status: "queued",
    owner: "gpt-pm",
    priority: report.humanApprovalNeeded.length || report.risks.length ? "high" : "normal",
    branch: "dev",
    attempts: 0,
    maxAttempts: 2,
    productionSafeMode: true,
    humanApprovalRequired: false,
    approvalTypes: [],
    createdAt: generatedAt,
    updatedAt: generatedAt,
    context: "Generated by human-confirmation-flow from latest Engineer Report.",
  };
}

function renderConfirmationRequired(result: HumanConfirmationResult, generatedAt: string): string {
  const risk = assessTaskRisk(result.task);
  return [
    "# Human Confirmation Required",
    "",
    `Updated: ${generatedAt}`,
    "",
    "## Status",
    `- Required: ${result.required ? "yes" : "no"}`,
    `- Approved: ${result.approved ? "yes" : "no"}`,
    `- Risk: ${risk.riskLevel}`,
    `- Reason: ${result.reason}`,
    "",
    "## GPT PM Question For Human Vision Owner",
    result.required
      ? `- Can Codex proceed with "${result.task.title}" within the approved scope, or should the task be rejected/modified?`
      : "- No human confirmation needed for the latest report.",
    "",
    "## Response Options",
    "- A. approve",
    "- B. reject",
    "- C. modify scope",
    "- D. rollback",
    "- E. ask GPT PM",
    "",
    "## Approval-Only Human Role",
    "- Human decides direction, approval, rejection, or scope.",
    "- AI handles log summary, retry proposal, codebase analysis, and safe handoff generation.",
    "- Human should not need to copy GPT answers into Codex; run `npm run agent:continue` after recording approval response.",
    "",
    "## Required Approval Response Format",
    `- Approval ID: approval-${result.task.id}`,
    `- Task: ${result.task.id}`,
    "- Status: approved | rejected",
    "- Approved By: Human Vision Owner",
    "- Approved Scope: <exact scope>",
    "- Expires At: <ISO timestamp>",
    "- Reason: <why>",
    "",
  ].join("\n");
}

function renderConfirmationLog(result: HumanConfirmationResult, generatedAt: string): string {
  return [
    "# Human Confirmation Log",
    "",
    `Generated: ${generatedAt}`,
    "",
    `- Task: ${result.task.id}`,
    `- Required: ${result.required ? "yes" : "no"}`,
    `- Approved: ${result.approved ? "yes" : "no"}`,
    `- Reason: ${result.reason}`,
    "- Production deploy: not performed",
    "- Rollback: not performed",
    "- env/API access: not used",
    "",
  ].join("\n");
}

function readOptional(projectRoot: string, relativePath: string): string {
  const fullPath = join(projectRoot, relativePath);
  return existsSync(fullPath) ? readFileSync(fullPath, "utf8") : "";
}

function ensureDirs(projectRoot: string): void {
  for (const dir of ["agent-memory", "logs"]) {
    const fullPath = join(projectRoot, dir);
    if (!existsSync(fullPath)) mkdirSync(fullPath, { recursive: true });
  }
}

function isDirectRun(): boolean {
  const entrypoint = process.argv[1];
  if (!entrypoint) return false;
  return import.meta.url === pathToFileURL(entrypoint).href;
}

if (isDirectRun()) {
  const result = runHumanConfirmationFlow(process.cwd());
  console.log("Human confirmation flow complete.");
  console.log(`Required: ${result.required ? "yes" : "no"}`);
  console.log(`Approved: ${result.approved ? "yes" : "no"}`);
  console.log(`Wrote: ${HUMAN_CONFIRMATION_REQUIRED_PATH}`);
  console.log(`Wrote: ${HUMAN_CONFIRMATION_LOG_PATH}`);
}
