import type { BugSeverity, TaskStatus, WorkflowTask } from "./orchestrator";
import { classifyBugSeverity } from "./orchestrator";

export type AgentPriority = WorkflowTask["priority"];

export interface MemorySnapshot {
  workflowStateMarkdown: string;
  openQuestionsMarkdown: string;
}

export interface PrioritizedTaskInput {
  title: string;
  goal: string;
  context: string;
  source: "workflow-state" | "open-questions" | "fallback";
}

export interface PriorityDecision {
  severity: BugSeverity;
  priority: AgentPriority;
  status: TaskStatus;
  humanApprovalRequired: boolean;
  blockedReason?: string;
  nextAction: string;
}

const HUMAN_APPROVAL_PATTERNS = [
  /production/i,
  /rollback/i,
  /deploy/i,
  /promote/i,
  /domain/i,
  /alias/i,
  /api key/i,
  /env/i,
  /secret/i,
  /token/i,
  /supabase schema/i,
  /permission/i,
  /billing/i,
  /paid/i,
  /upgrade/i,
];

const BLOCKED_PATTERNS = [/blocked/i, /approval/i, /2fa/i, /password/i, /permission denied/i, /missing env/i];

export function extractNextTaskInput(snapshot: MemorySnapshot): PrioritizedTaskInput {
  const explicitNextTask = readFirstListItemAfterHeading(snapshot.workflowStateMarkdown, "Next Suggested Task");
  if (explicitNextTask) {
    return {
      title: explicitNextTask,
      goal: explicitNextTask,
      context: "Generated from agent-memory/workflow-state.md",
      source: "workflow-state",
    };
  }

  const openQuestion = readFirstListItemAfterHeading(snapshot.openQuestionsMarkdown, "Pending");
  if (openQuestion) {
    return {
      title: `Resolve PM question: ${openQuestion}`,
      goal: "Clarify the highest-impact open question before engineering continues.",
      context: "Generated from agent-memory/open-questions.md",
      source: "open-questions",
    };
  }

  return {
    title: "Ask GPT PM Agent for the next prioritized task",
    goal: "No active queue item or open question was found.",
    context: "Generated by fallback priority engine.",
    source: "fallback",
  };
}

export function decidePriority(input: PrioritizedTaskInput): PriorityDecision {
  const combined = `${input.title}\n${input.goal}\n${input.context}`;
  const severity = classifyBugSeverity(combined);
  const humanApprovalRequired = HUMAN_APPROVAL_PATTERNS.some((pattern) => pattern.test(combined));
  const blocked = BLOCKED_PATTERNS.some((pattern) => pattern.test(combined));
  const priority = severityToPriority(severity, humanApprovalRequired);

  if (humanApprovalRequired) {
    return {
      severity,
      priority,
      status: "needs_human_approval",
      humanApprovalRequired: true,
      blockedReason: "Task references production, env, permissions, or another approval-gated area.",
      nextAction: "Request human approval before continuing.",
    };
  }

  if (blocked) {
    return {
      severity,
      priority,
      status: "blocked",
      humanApprovalRequired: false,
      blockedReason: "Memory indicates a blocked state.",
      nextAction: "Ask GPT PM Agent to clarify the blocker.",
    };
  }

  return {
    severity,
    priority,
    status: "queued",
    humanApprovalRequired: false,
    nextAction: input.source === "open-questions" ? "Ask GPT PM Agent for clarification." : "Create Codex handoff.",
  };
}

export function createTaskFromDecision(input: PrioritizedTaskInput, decision: PriorityDecision): WorkflowTask {
  const now = new Date().toISOString();
  return {
    id: createTaskId(input.title),
    title: input.title,
    goal: input.goal,
    status: decision.status,
    owner: decision.status === "needs_human_approval" ? "human" : "codex-engineer",
    priority: decision.priority,
    branch: "dev",
    attempts: 0,
    maxAttempts: decision.severity === "s0-production-down" ? 1 : 2,
    productionSafeMode: true,
    humanApprovalRequired: decision.humanApprovalRequired,
    approvalTypes: decision.humanApprovalRequired ? ["production_deploy"] : [],
    createdAt: now,
    updatedAt: now,
    context: input.context,
    blockedReason: decision.blockedReason,
    validationRequired: ["npm run build"],
    nextSuggestedTask: decision.nextAction,
  };
}

export function recommendNextAction(task: WorkflowTask, decision: PriorityDecision): string {
  if (task.status === "needs_human_approval") {
    return `Human approval required before ${task.title}`;
  }

  if (task.status === "blocked") {
    return `Send blocker to GPT PM Agent: ${task.blockedReason ?? "No blocker details provided."}`;
  }

  if (decision.severity === "s0-production-down") {
    return "Prepare a stability-first recovery handoff and avoid UX enhancements.";
  }

  return "Generate Codex handoff and proceed on dev with build validation.";
}

function severityToPriority(severity: BugSeverity, humanApprovalRequired: boolean): AgentPriority {
  if (humanApprovalRequired || severity === "s0-production-down") return "urgent";
  if (severity === "s1-critical") return "high";
  if (severity === "s2-major") return "normal";
  return "low";
}

function readFirstListItemAfterHeading(markdown: string, heading: string): string | undefined {
  const match = markdown.match(new RegExp(`##\\s+${escapeRegExp(heading)}\\s*\\n([\\s\\S]*?)(?=\\n##\\s+|$)`, "i"));
  const section = match?.[1] ?? "";
  return section
    .split("\n")
    .map((line) => line.replace(/^\s*-\s*/, "").trim())
    .find((line) => line.length > 0 && !line.startsWith("|") && !line.includes("---"));
}

function createTaskId(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
  return `auto-${slug || "task"}`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
